version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: postgre
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: "${DB_USER_ID}"
        POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
        - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
