version: "3.7"

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
