apps:
  - name: "ngrok run"
    script: "./ngrok"
    args: "start --all -config ./ngrok.yml"
    instances: "1"
    autorestart: true
    max_restarts: 20
    max_memory_restart: "500M"
    watch: false
    error_file: "err-prod.log"
    out_file: "out-prod.log"
    log_file: "combined-prod.log"
