# Step1
## 노드를 빌드하고 실행시키는 이미지를 가져온다.
FROM node:16.13
# EXPOSE 30000 32000 33000

#Proejct의 모든 파일을 WORKDIR == /app 으로 복사한다.
WORKDIR /app

#ngrok 배포를 위한 공통 설정
COPY ./srcs/deploy/ngrok .
COPY ./srcs/deploy/pm2-ngrok.yml .
RUN npm i -g pm2

COPY ./srcs/back_end .
# bcrypt linux 에서 받아야 오류가 안난다고함..
RUN yarn add bcrypt
RUN yarn
RUN yarn build

ENTRYPOINT [ "bash" ]
CMD [ "start.sh" ]