version: "3"

services:
  db:
    image: postgres:13.5-alpine
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    networks:
      - ts_network
    # volumes:
    #   - ${POSTGRES_HOME_DIR}/data/:/var/lib/postgresql/data
  api.ts.io:
    container_name: back_end
    build: ${BACKEND_PATH}
    ports:
      - 30000:30000
    networks:
      - ts_network
    depends_on:
      - db

  ts.io:
    container_name: front_end
    build: ${FRONTEND_PATH}
    ports:
      - 3000:3000
    networks:
      - ts_network
    depends_on:
      - db
      - api.ts.io

networks:
  ts_network:
    driver: bridge
