# Step1
## 노드를 빌드하고 실행시키는 이미지를 가져온다.
FROM node:16.13
EXPOSE 30000 32000 33000 

WORKDIR /app
#Proejct의 모든 파일을 WORKDIR == /app 으로 복사한다.
COPY ./srcs/back_end .
RUN yarn
RUN yarn build

ENTRYPOINT [ "node" ]
CMD [ "dist/main.js" ]